package cn.jinelei.rainbow.constant


//权限请求码
const val REQUEST_CODE_ACCESS_WIFI_STATE = 0x01
const val REQUEST_CODE_CHANGE_WIFI_STATE = 0x02
const val REQUEST_CODE_ACCESS_COARSE_LOCATION = 0x03
const val REQUEST_CODE_WRITE_EXTERNAL_STORAGE = 0x04
const val REQUEST_CODE_ACCESS_NETWORK_STATE = 0x05

//首选项
const val PRE_NAME_USER = "PRE_NAME_USER"
const val PRE_KEY_DEBUG = "PRE_KEY_DEBUG"
const val PRE_KEY_LANGUAGE = "PRE_KEY_LANGUAGE"

