package cn.jinelei.rainbow.constant


const val REQUEST_CODE_ACCESS_WIFI_STATE = 0x01
const val REQUEST_CODE_CHANGE_WIFI_STATE = 0x02
const val REQUEST_CODE_ACCESS_COARSE_LOCATION = 0x03
const val REQUEST_CODE_WRITE_EXTERNAL_STORAGE = 0x04
